/*
 * uuid_i.h
 *
 *  Created on: 2012/12/14
 *      Author: SUCHEN
 */

#ifndef UUID_I_H_
#define UUID_I_H_

EXTERN_C const GUID TIME_FORMAT_NONE;
EXTERN_C const GUID TIME_FORMAT_FRAME;
EXTERN_C const GUID TIME_FORMAT_BYTE;
EXTERN_C const GUID TIME_FORMAT_SAMPLE;
EXTERN_C const GUID TIME_FORMAT_FIELD;
EXTERN_C const GUID TIME_FORMAT_MEDIA_TIME;

#endif /* UUID_I_H_ */
